<?php echo $this->doctype() ?>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="chrome=1">
	<meta http-equiv="Content-Type" content="text/html" charset="utf-8">
	<title>Contactos Alegra</title>
	<?php
		echo $this->headLink()
			->appendStylesheet('js/resources/css/ext-all-neptune.css');
		echo $this->headScript()
			->appendFile('js/ext-all-debug.js')
			->appendFile('js/app.js');
	?>
</head>
<body>
	<?php  echo $this->layout()->content ?>
</body>
</html>
